# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4c4ca580b775b261c6af799a91ab22489cc235eb0f97e1bfc7019683cebf093f95deaacfa22cececb75f2a0e9a4e4994b9a1c2c64b8f62d86a30db7f518884aa

test:
  secret_key_base: 4d74c950c4daf1f34ded6c7654c6d206ff842fe3960521f83ecfc3f73a28651b3d1404564fdba576b11618b02f64930effe5c3557d569324b38c67b26f7e068d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
